@server = http://localhost
@port = 3000
@api_path = api
@api_version = 1
@url = {{server}}:{{port}}/{{api_path}}/v{{api_version}}

###############################################

// Test: Get all pets
GET {{url}}/pets

###############################################

// Test: Get a specific pet
GET {{url}}/pets/Lucy

###############################################

// Test: Get all pets of an owner
GET {{url}}/owners/19850930-5678

###############################################

GET {{url}}/owners

###############################################

POST {{url}}/pets HTTP/1.1
Content-Type: application/json

{
  "petName": "Skunken",
  "species": "Dog",
  "breed": "Golden Retriever",
  "color": "White Cream",
  "birthdate": "2000-05-05",
  "healthStatus": "Healthy",
  "ownerSsn": "19730418-7890"
}

###############################################

POST {{url}}/owners HTTP/1.1
Content-Type: application/json

{
  "ownerName": "Kalle Kula",
  "address": "Kallebacken 1",
  "phone": "070-1234567",
  "email": "k.kula@mail.com",
  "ownerSsn": "12345678-1234"
}

###############################################

PUT {{url}}/pets/Skunken HTTP/1.1
Content-Type: application/json

{
  "healthStatus": "Sick"
}

###############################################

DELETE {{url}}/pets/Skunken/19730418-7890

