@server = http://localhost
@port = 3000
@api_path = api
@api_version = 1
@url = {{server}}:{{port}}/{{api_path}}/v{{api_version}}

###############################################

// Test: Get all miun courses
// Expected HTTP response status code: 200
// Expected response: an array (json) with all courses (including subject for each course)
// [{}, {}, ...]
GET {{url}}/pets

###############################################

// Test: Get a specific pet
GET {{url}}/pets/Bella

###############################################
// Test: Get all pets of an owner
GET {{url}}/owners/19730418-7890


###############################################
GET {{url}}/owners

###############################################
GET {{url}}/pets/Dog

###############################################
POST {{url}}/pets HTTP/1.1
Content-Type: application/json

{
  "name": "Skunken",
  "species": "Dog",
  "breed": "Golden Retriever",
  "birthdate": "2000-05-05",
  "healthStatus": "Healthy",
  "ownerSsn": "19730418-7890"
}

###############################################
PUT {{url}}/pets/Skunken HTTP/1.1
Content-Type: application/json

{
  "healthStatus": "Sick"
}
